// -----------------------------------------------------------------------
// <copyright file="RuleRewriter.cs" company="">
// BSD Licence
// </copyright>
// -----------------------------------------------------------------------

namespace StyleCopMagic
{
    using System.Linq;
    using Roslyn.Compilers.CSharp;

    public abstract class RuleRewriter : SyntaxRewriter
    {
        public static bool IsAutogenerated(SyntaxNode contents)
        {
            return contents.GetLeadingTrivia().Any(x => x.ToFullString().Contains("<auto-generated"));
        }
    }
}
