// -----------------------------------------------------------------------
// <copyright file="SettingsFileTest.cs" company="">
// BSD Licence
// </copyright>
// -----------------------------------------------------------------------

namespace StyleCopMagic.UnitTests
{
    using System.IO;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Roslyn.Compilers.CSharp;

    [TestClass]
    public class RuleRewriterTest
    {
        [TestMethod]
        public void IsAutogenerated_Detects_Autogenerated_Header()
        {
            string path = Path.Combine(TestBase.TestFilePath, "RuleRewriter", "Autogenerated.cs");
            SyntaxTree tree = SyntaxTree.ParseFile(path);

            Assert.IsTrue(RuleRewriter.IsAutogenerated(tree.GetRoot()));
        }
    }
}
